"""Ajout du champ rappel_envoye

Revision ID: 314fca943259
Revises: 
Create Date: 2026-07-07 01:23:20.429492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314fca943259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(
    sa.Column(
        'rappel_envoye',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('rappel_envoye')

    # ### end Alembic commands ###
